favicon: https://data.calacaly.cn/favicon.ico

avatar:
  img: https://data.calacaly.cn/avatar.ico
  effect: fales

disable_top_img: false

index_img:

error_404:
  enable: true
  subitle: "Page Not Found"
  background: https://pitures.calacal.cn/

error_img:
  flink: /img/friend_404.gif
  post_page: /img:404.jpg

menu:
  é¦–é¡µ: / || fas fa-home
  æ ‡ç­¾: /tags/ || fas fa-tags
  åˆ†ç±»: /categories/ || fas fa-folder-open
  åˆ—è¡¨||fas fa-list || hide:
    éŸ³ä¹: /music/ || fas famusic
    å›¾ç‰‡: /pictures/
  å‹é“¾: /link/ || fas fa-link
  å…³äº: /about/ || fas fa-heart

highlight_theme: mac
highlight_copy: true
highlight_lang: true
highlight_shrink: false
highlight_height_limit: 230
code_word_wrap: false

# copy settings
# copyright: Add the copyright information after copied content (å¤åˆ¶çš„å†…å®¹åé¢åŠ ä¸Šç‰ˆæƒä¿¡æ¯)
copy:
  enable: true # æ˜¯å¦å¼€å¯ç½‘ç«™å¤åˆ¶æƒé™
  copyright: # å¤åˆ¶çš„å†…å®¹åé¢åŠ ä¸Šç‰ˆæƒä¿¡æ¯
    enable: true # æ˜¯å¦å¼€å¯å¤åˆ¶ç‰ˆæƒä¿¡æ¯æ·»åŠ 
    limit_count: 50 # å­—æ•°é™åˆ¶ï¼Œå½“å¤åˆ¶æ–‡å­—å¤§äºè¿™ä¸ªå­—æ•°é™åˆ¶æ—¶ï¼Œå°†åœ¨å¤åˆ¶çš„å†…å®¹åé¢åŠ ä¸Šç‰ˆæƒä¿¡æ¯

social:
  fab fa-github: https://github.com/calacaly || Github
  fas fa-envelope: "mailto: calacaly@yandex.com || Email"

algolia_search:
  enable: false
  hits:
    per_page: 6

local_search:
  enable: true
  preload: false
  CND:

post_meta:
  page:
    date_type: both # created or updated or both ä¸»é¡µæ–‡ç« æ—¥æœŸæ˜¯åˆ›å»ºæ—¥æˆ–è€…æ›´æ–°æ—¥æˆ–éƒ½æ˜¾ç¤º
    date_format: relative # date/relative æ˜¾ç¤ºæ—¥æœŸè¿˜æ˜¯ç›¸å¯¹æ—¥æœŸ
    categories: true # true or false ä¸»é¡µæ˜¯å¦æ˜¾ç¤ºåˆ†ç±»
    tags: true # true or false ä¸»é¡µæ˜¯å¦æ˜¾ç¤ºæ ‡ç­¾
    label: true # true or false æ˜¾ç¤ºæè¿°æ€§æ–‡å­—
  post:
    date_type: both # created or updated or both æ–‡ç« é¡µæ—¥æœŸæ˜¯åˆ›å»ºæ—¥æˆ–è€…æ›´æ–°æ—¥æˆ–éƒ½æ˜¾ç¤º
    date_format: relative # date/relative æ˜¾ç¤ºæ—¥æœŸè¿˜æ˜¯ç›¸å¯¹æ—¥æœŸ
    categories: true # true or false æ–‡ç« é¡µæ˜¯å¦æ˜¾ç¤ºåˆ†ç±»
    tags: true # true or false æ–‡ç« é¡µæ˜¯å¦æ˜¾ç¤ºæ ‡ç­¾
    label: true # true or false æ˜¾ç¤ºæè¿°æ€§æ–‡å­—

index_post_content:
  method: 3
  length: 500

toc:
  post: true # æ–‡ç« é¡µæ˜¯å¦æ˜¾ç¤º TOC
  page: false # æ™®é€šé¡µé¢æ˜¯å¦æ˜¾ç¤º TOC
  number: true # æ˜¯å¦æ˜¾ç¤ºç« èŠ‚æ•°
  expand: false # æ˜¯å¦å±•å¼€ TOC
  style_simple: false # for post ç®€æ´æ¨¡å¼ï¼ˆä¾§è¾¹æ åªæ˜¾ç¤º TOC, åªå¯¹æ–‡ç« é¡µæœ‰æ•ˆ ï¼‰

post_copyright:
  enable: true
  decode: false
  author_href:
  license: CC BY-NC-SA 4.0
  license_url: https://creativecommons.org/licenses/by-nc-sa/4.0/
copyright_author: xxxx
copyright_author_href: https://xxxxxx.com
copyright_url: https://xxxxxx.com
copyright_info: æ­¤æ–‡ç« ç‰ˆæƒå½’xxxxxæ‰€æœ‰ï¼Œå¦‚æœ‰è½¬è½½ï¼Œè¯·è¨»æ˜æ¥è‡ªåŸä½œè€…

related_post:
  enable: true
  limit: 6 # æ˜¾ç¤ºæ¨èæ–‡ç« æ•°ç›®
  date_type: created # or created or updated æ–‡ç« æ—¥æœŸæ˜¾ç¤ºåˆ›å»ºæ—¥æˆ–è€…æ›´æ–°æ—¥

reward:
  enable: false
  QR_code:
    - img: /img/wechat.jpg
      link:
      text: wechat
    - img: /img/alipay.jpg
      link:
      text: alipay

# anchor
# when you scroll in post , the url will update according to header id.
anchor: true

# post_pagination (åˆ†é¡µ)
# value: 1 || 2 || false	# false:ä¸ºå…³é—­åˆ†é¡µæŒ‰é’®ï¼›1:ä¸‹ä¸€ç¯‡æ˜¾ç¤ºçš„æ˜¯æ—§æ–‡ç« ï¼›2:ä¸‹ä¸€ç¯‡æ˜¾ç¤ºçš„æ˜¯æ–°æ–‡ç« 
# 1: The 'next post' will link to old post
# 2: The 'next post' will link to new post
# false: disable pagination
post_pagination: false

# Displays outdated notice for a post (æ–‡ç« è¿‡æœŸæé†’)
noticeOutdate:
  enable: true
  style: flat # style: simple/flat
  limit_day: 365 # è·ç¦»æ›´æ–°æ—¶é—´å¤šå°‘å¤©æ‰æ˜¾ç¤ºæ–‡ç« è¿‡æœŸæé†’
  position: top # position: top/bottom
  message_prev: It has been # å¤©æ•°ä¹‹å‰çš„æ–‡å­—
  message_next: days since the last update, the content of the article may be outdated. # å¤©æ•°ä¹‹åçš„æ–‡å­—

addThis:
  enable: false
  pubid:

sharejs:
  enable: true
  sites: facebook,twitter.wechat,weibo,qq

footer:
  owner:
    enable: true
    since: 2022 # ç«™ç‚¹èµ·å§‹æ—¶é—´
  custom_text: The sunshine is just right.<p><a target="_blank" href="https://hexo.io/"><img src="https://img.shields.io/badge/Frame-Hexo-blue?style=flat&logo=hexo" title="åšå®¢æ¡†æ¶ä¸ºHexo"></a>&nbsp;<a target="_blank" href="https://butterfly.js.org/"><img src="https://img.shields.io/badge/Theme-Butterfly-6513df?style=flat&logo=bitdefender" title="ä¸»é¢˜é‡‡ç”¨butterfly"></a>&nbsp;<a target="_blank" href="https://www.jsdelivr.com/"><img src="https://img.shields.io/badge/CDN-jsDelivr-orange?style=flat&logo=jsDelivr" title="æœ¬ç«™ä½¿ç”¨JsDelivrä¸ºé™æ€èµ„æºæä¾›CDNåŠ é€Ÿ"></a> &nbsp;</a>&nbsp;<a target="_blank" href="https://github.com/"><img src="https://img.shields.io/badge/Source-Github-d021d6?style=flat&logo=GitHub" title="æœ¬ç«™é¡¹ç›®ç”±Gtihubæ‰˜ç®¡"></a>&nbsp;<a target="_blank" href="http://creativecommons.org/licenses/by-nc-sa/4.0/"><img src="https://img.shields.io/badge/Copyright-BY--NC--SA%204.0-d42328?style=flat&logo=Claris" title="æœ¬ç«™é‡‡ç”¨çŸ¥è¯†å…±äº«ç½²å-éå•†ä¸šæ€§ä½¿ç”¨-ç›¸åŒæ–¹å¼å…±äº«4.0å›½é™…è®¸å¯åè®®è¿›è¡Œè®¸å¯"></a></p>
  copyright: false # Copyright of theme and framework

cover:
  # æ˜¯å¦æ˜¾ç¤ºæ–‡ç« å°é¢
  index_enable: true
  aside_enable: true
  archives_enable: true
  # å°é¢æ˜¾ç¤ºçš„ä½ç½®
  # ä¸‰ä¸ªå€¼å¯é…ç½® left , right , both
  position: both
  # å½“æ²¡æœ‰è®¾ç½®coveræ—¶ï¼Œé»˜è®¤çš„å°é¢æ˜¾ç¤º
  default_cover:

default_cover:
  - https://cdn.jsdelivr.net/gh/jerryc127/CDN@latest/cover/default_bg.png
  - https://cdn.jsdelivr.net/gh/jerryc127/CDN@latest/cover/default_bg2.png
  - https://cdn.jsdelivr.net/gh/jerryc127/CDN@latest/cover/default_bg3.png

translate:
  enable: false
  # é»˜è®¤æŒ‰é’®æ˜¾ç¤ºæ–‡å­—(ç½‘ç«™æ˜¯ç®€ä½“ï¼Œåº”è®¾ç½®ä¸º'default: ç¹')
  default: ç®€
  # the language of website (1 - Traditional Chinese/ 2 - Simplified Chineseï¼‰
  # ç½‘ç«™é»˜è®¤è¯­è¨€ï¼Œ1: ç¹ä½“ä¸­æ–‡, 2: ç®€ä½“ä¸­æ–‡
  defaultEncoding: 2
  # Time delay å»¶è¿Ÿæ—¶é—´,è‹¥ä¸åœ¨å‰, è¦è®¾å®šå»¶è¿Ÿç¿»è¯‘æ—¶é—´, å¦‚100è¡¨ç¤º100ms,é»˜è®¤ä¸º0
  translateDelay: 0
  # å½“æ–‡å­—æ˜¯ç®€ä½“æ—¶ï¼ŒæŒ‰é’®æ˜¾ç¤ºçš„æ–‡å­—
  msgToTraditionalChinese: "ç¹"
  # å½“æ–‡å­—æ˜¯ç¹ä½“æ—¶ï¼ŒæŒ‰é’®æ˜¾ç¤ºçš„æ–‡å­—
  msgToSimplifiedChinese: "ç°¡"

# dark mode
darkmode:
  enable: false
  # dark å’Œ light ä¸¤ç§æ¨¡å¼åˆ‡æ¢æŒ‰é’®
  button: true
  # Switch dark/light mode automatically (è‡ªå‹•åˆ‡æ› dark modeå’Œ light mode)
  # autoChangeMode: 1  Following System Settings, if the system doesn't support dark mode, it will switch dark mode between 6 pm to 6 am
  # autoChangeMode: 2  Switch dark mode between 6 pm to 6 am
  # autoChangeMode: false
  autoChangeMode: false

readmode: true

aside:
  enable: true
  hide: false
  button: true
  mobile: true # display on mobile
  position: right # left or right
  display:
    archive: true
    tag: true
    category: true
  card_author:
    enable: true
    description:
    button:
      enable: true
      icon: # fab fa-github
      text: ğŸ›´å‰å¾€å°å®¶...
      link: https://github.com/calacaly
  card_announcement:
    enable: false
    content: <center><a href="https://blog.calacaly.cn"><b><font color="#5ea6e5">blog.calacaly.cn</font></b></a><br><a href="https://blog.calacaly.cn"><b><font color="#5ea6e5">blog.calacaly.cn</font></b></a><br><a href="mailto:calacaly@yandex.com"><b><font color="#a591e0">calacaly@yandex.com</font></b></a></center>
  card_recent_post:
    enable: false
    limit: 3 # if set 0 will show all
    sort: date # date or updated
    sort_order: # Don't modify the setting unless you know how it works
  card_categories:
    enable: false
    limit: 8 # if set 0 will show all
    expand: none # none/true/false
    sort_order: # Don't modify the setting unless you know how it works
  card_tags:
    enable: false
    limit: 20 # if set 0 will show all
    color: true
    sort_order: # Don't modify the setting unless you know how it works
  card_archives:
    enable: false
    type: monthly # yearly or monthly
    format: MMMM YYYY # eg: YYYYå¹´MMæœˆ
    order: -1 # Sort of order. 1, asc for ascending; -1, desc for descending
    limit: 8 # if set 0 will show all
    sort_order: # Don't modify the setting unless you know how it works
  card_webinfo:
    enable: true
    post_count: true
    last_push_date: true
    sort_order: # Don't modify the setting unless you know how it works
  card_weibo:
    enable: true

busuanzi:
  site_uv: true # æœ¬ç«™æ€»è®¿å®¢æ•°
  site_pv: true # æœ¬ç«™æ€»è®¿é—®é‡
  page_pv: true # æœ¬æ–‡æ€»é˜…è¯»é‡

# Time difference between publish date and now (ç¶²é é‹è¡Œæ™‚é–“)
# Formal: Month/Day/Year Time or Year/Month/Day Time
runtimeshow:
  enable: false
  publish_date: 8/9/2022 00:00:00
  ##ç½‘é¡µå¼€é€šæ—¶é—´
  #æ ¼å¼: æœˆ/æ—¥/å¹´ æ—¶é—´
  #ä¹Ÿå¯ä»¥å†™æˆ å¹´/æœˆ/æ—¥ æ—¶é—´

# Aside widget - Newest Comments
newest_comments:
  enable: true
  sort_order: # Don't modify the setting unless you know how it works
  limit: 6 # æ˜¾ç¤ºçš„æ•°é‡
  storage: 10 # è®¾ç½®ç¼“å­˜æ—¶é—´ï¼Œå•ä½ åˆ†é’Ÿ
  avatar: true # æ˜¯å¦æ˜¾ç¤ºå¤´åƒ

# å›¾ç‰‡æ ¼å¼ url(http://xxxxxx.com/xxx.jpg)
# é¢œè‰²ï¼ˆHEXå€¼/RGBå€¼/é¢œè‰²å•è¯/æ¸å˜è‰²)
# ç•™ç©º ä¸æ˜¾ç¤ºèƒŒæ™¯
background: url(https://source.fomal.cc/img/dm1.webp)

# Typewriter Effect (æ‰“å­—æ•ˆæœ)
# https://github.com/disjukr/activate-power-mode
activate_power_mode:
  enable: false
  colorful: true # open particle animation (å†’å…‰ç‰¹æ•ˆ)
  shake: true #  open shake (æŠ–å‹•ç‰¹æ•ˆ)
  mobile: false

# footeræ˜¯å¦æ˜¾ç¤ºå›¾ç‰‡èƒŒæ™¯(ä¸top_imgä¸€è‡´)
footer_bg: true

canvas_fluttering_ribbon:
  enable: true
  mobile: true # false æ‰‹æœºç«¯ä¸æ˜¾ç¤º true æ‰‹æœºç«¯æ˜¾ç¤º

fireworks:
  enable: true
  zIndex: 9999 # -1 or 9999
  mobile: false

# Global font settings
# Don't modify the following settings unless you know how they work (éå¿…è¦ä¸è¦ä¿®æ”¹)
font:
  global-font-size: "15px"
  code-font-size: "14px"
  # -apple-system, BlinkMacSystemFont, "Segoe UI" , "Helvetica Neue" , Lato, Roboto, "PingFang SC" , "Microsoft JhengHei" , "Microsoft YaHei" , sans-serif
  # Wenkai, consolas, -apple-system, 'Quicksand', 'Nimbus Roman No9 L', 'PingFang SC', 'Hiragino Sans GB', 'Noto Serif SC', 'Microsoft Yahei', 'WenQuanYi Micro Hei', 'ST Heiti', sans-serif;
  font-family: var(--global-font), Consolas_1, -apple-system, 'Quicksand', 'Nimbus Roman No9 L', 'PingFang SC', 'Hiragino Sans GB', 'Noto Serif SC', 'Microsoft Yahei', 'WenQuanYi Micro Hei', 'ST Heiti', sans-serif;
  # consolas, ZhuZiAWan_light, "Microsoft YaHei", Menlo, "PingFang SC", "Microsoft JhengHei", sans-serif
  # Consolas_1, ZhuZiAWan_light, "Microsoft YaHei", Menlo, "PingFang SC", "Microsoft JhengHei", sans-serif
  code-font-family: Consolas_1, var(--global-font), "Microsoft YaHei", Menlo, "PingFang SC", "Microsoft JhengHei", sans-serif

# Font settings for the site title and site subtitle
# https://fonts.googleapis.com/css?family=Titillium+Web&display=swap
# Titillium Web, 'PingFang SC' , 'Hiragino Sans GB' , 'Microsoft JhengHei' , 'Microsoft YaHei' , sans-serif
# å·¦ä¸Šè§’ç¶²ç«™åå­— ä¸»é å±…ä¸­ç¶²ç«™åå­—
blog_title_font:
  font_link:
  font-family: var(--global-font)

# the subtitle on homepage (ä¸»é subtitle)
subtitle:
  enable: true
  # Typewriter Effect (æ‰“å­—æ•ˆæœ)
  effect: true
  # loop (å¾ªç’°æ‰“å­—)
  loop: false
  # source èª¿ç”¨ç¬¬ä¸‰æ–¹æœå‹™
  # source: false é—œé–‰èª¿ç”¨
  # source: 1  èª¿ç”¨ä¸€è¨€ç¶²çš„ä¸€å¥è©±ï¼ˆç°¡é«”ï¼‰ https://hitokoto.cn/
  # source: 2  èª¿ç”¨ä¸€å¥ç¶²ï¼ˆç°¡é«”ï¼‰ http://yijuzhan.com/
  # source: 3  èª¿ç”¨ä»Šæ—¥è©©è©ï¼ˆç°¡é«”ï¼‰ https://www.jinrishici.com/
  # subtitle æœƒå…ˆé¡¯ç¤º source , å†é¡¯ç¤º sub çš„å…§å®¹
  source: false
  # å¦‚æœé—œé–‰æ‰“å­—æ•ˆæœï¼Œsubtitle åªæœƒé¡¯ç¤º sub çš„ç¬¬ä¸€è¡Œæ–‡å­—
  sub:
    - "Welcome to CacalyğŸ¥blog Home!ğŸ¤£ğŸ¤£ğŸ¤£"
    - "Hope you have a nice day!ğŸ­ğŸ­ğŸ­"

# åŠ è½½åŠ¨ç”» Loading Animation
preloader: true

wordcount:
  enable: true
  post_wordcount: true
  min2read: true
  total_wordcount: true

# fancybox http://fancyapps.com/fancybox/3/
fancybox: true

# Pjax [Beta]
# It may contain bugs and unstable, give feedback when you find the bugs.
# https://github.com/MoOx/pjax
pjax:
  enable: true
  # å¯¹äºä¸€äº›ç¬¬ä¸‰æ–¹æ’ä»¶ï¼Œæœ‰äº›å¹¶ä¸æ”¯æŒ pjax ã€‚
  # ä½ å¯ä»¥æŠŠç½‘é¡µåŠ å…¥åˆ° exclude é‡Œï¼Œè¿™ä¸ªç½‘é¡µä¼šè¢« pjax æ’é™¤åœ¨å¤–ã€‚
  # ç‚¹å‡»è¯¥ç½‘é¡µä¼šé‡æ–°åŠ è½½ç½‘ç«™ã€‚
  exclude:
    - /music/
    - /no-pjax/

# Inject
# Insert the code to head (before '</head>' tag) and the bottom (before '</body>' tag)
# æ’å…¥ä»£ç åˆ°å¤´éƒ¨ </head> ä¹‹å‰ å’Œ åº•éƒ¨ </body> ä¹‹å‰
inject:
  head:
    - <link rel="stylesheet" href="/css/custom.css">
  bottom:
    - <script src="xxxx"></script>
